global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node-backend'
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']

